object Versions {
    const val composeCompilerVersion = "1.4.3"
    const val dataBindingCompilerVersion = "1.4.3"
    const val lifecycleVersion = "2.4.1"
    const val roomDBVersion = "2.5.0"
    const val composeVersion = "1.4.5"
    const val composeUIVersion = "1.4.0-rc01"
    const val wearComposeVersion = "1.1.2"
    const val workVersion = "2.8.0"
    const val navVersion = "2.4.1"
    const val exoPlayerVersion = "2.18.0"
    const val pagingLibraryVersion = "3.1.0"
    const val multiDexVersion = "2.0.1"
    const val wearOSComposeVersion = "1.1.2"
}